#!/bin/sh /etc/rc.common
# procd-Service fuer tun2socks (liest von tun0, leitet an Xray-SOCKS 10808)
START=99
STOP=10
USE_PROCD=1
PROG=/usr/bin/tun2socks
start_service() {
    [ -x "$PROG" ] || return 1
    procd_open_instance
    procd_set_param command "$PROG" -device tun0 -proxy socks5://127.0.0.1:10808 -loglevel warning
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
